### ISSUE TITLE
Add dark mode support

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/steveklabnik.com#87]
### Summary
Implement a dark mode theme to reduce eye strain and provide a better reading experience for users who prefer dark interfaces.

### Implementation Details
- **Theme Switcher**: Toggle button in header to switch between light/dark
- **System Preference**: Respect user's OS-level dark mode preference by default
- **Persistence**: Save preference in localStorage
- **Smooth Transitions**: Animate theme changes for better UX

### Technical Approach
1. Use CSS custom properties for theme colors:
   ```css
   :root {
     --bg-color: #f8fafc;
     --text-color: #1e293b;
     --link-color: #2563eb;
   }
   
   [data-theme="dark"] {
     --bg-color: #0f172a;
     --text-color: #e2e8f0;
     --link-color: #60a5fa;
   }
   ```

2. JavaScript theme toggle:
   - Check localStorage and system preference on load
   - Toggle class on document root
   - Save preference to localStorage

3. Prevent flash of incorrect theme:
   - Inline script in <head> to set theme before paint

### Design Considerations
- Maintain readability with proper contrast ratios
- Adjust code block themes for dark mode
- Consider dimmed images in dark mode
- Ensure all UI elements work in both themes

### Benefits
- Reduces eye strain in low-light conditions
- Follows modern web standards and user expectations
- Improves accessibility for light-sensitive users
- Professional feature expected in tech blogs

### Alternatives Considered
- CSS-only with prefers-color-scheme (no manual toggle)
- Multiple theme options beyond light/dark (adds complexity)
